#if defined _modularstore_globals_included
  #endinput
#endif
#define _modularstore_globals_included

#define MAX_CATEGORY_NAME_LENGTH 64
#define MAX_ITEM_NAME_LENGTH 64
#define MAX_TYPE_NAME_LENGTH 64
#define MAX_DISPLAY_NAME_LENGTH 64
#define MAX_ACTION_NAME_LENGTH 64
#define MAX_PACKAGE_NAME_LENGTH 64
#define MAX_STATUS_NAME_LENGTH 64
#define MAX_CURRENCY_NAME_LENGTH 64
#define MAX_DISTRIBUTION_NAME_LENGTH 64
#define MAX_DESCRIPTION_LENGTH 128
#define MAX_ACTIONS_LENGTH 512

//Store Actions
#define STORE_ITEMACTION_ALL  "all"
#define STORE_ITEMACTION_BUY  "buy"
#define STORE_ITEMACTION_SELL "sell"
#define STORE_ITEMACTION_EQUIP "equip"
#define STORE_ITEMACTION_UNEQUIP "unequip"
#define STORE_ITEMACTION_PREVIEW "preview"
#define STORE_ITEMACTION_GIFT "gift"
#define STORE_ITEMACTION_TRADE "trade"
#define STORE_ITEMACTION_AUCTION "auction"
#define STORE_ITEMACTION_GIVEAWAY "giveaway"
